name: Deploy to Shared Hosting

on:
  push:
    branches:
      - main  # Change this if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Shared Hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4  # Updated version
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.REMOTE_PATH }}
          protocol: ftp  # Change to "sftp" if using SFTP
          port: ${{ secrets.FTP_PORT }}
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/README.md
